# Generated by Django 6.0.5 on 2026-05-26 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referralreward',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to='orders.order'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_reward_source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='referralreward',
            unique_together={('referrer', 'referred_user', 'order')},
        ),
    ]
